import {
  ClerkProvider, 
} from '@clerk/nextjs'
import type { Metadata } from "next";
import {  Poppins } from "next/font/google";
import "./globals.css";
import '@stream-io/video-react-sdk/dist/css/styles.css';
import 'react-datepicker/dist/react-datepicker.css';
const inter = Poppins({ subsets: ["latin"], weight:["400", "500","600","700","800","900"] });

export const metadata :Metadata = {
  title: "Account",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
       <ClerkProvider>
      <body className={inter.className}>
      
        {children}
        </body>
       </ClerkProvider>
    </html>
  );
}
